image: gcc

stages:
  - build
  - test

build:
  stage: build
  before_script:
    - apt update && apt -y install cmake
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
  artifacts:
    paths:
      - build/
    expire_in: 1 week

test-lab2:
  stage: test
  script:
    - ./build/test/runtests
